### ISSUE TITLE
React Icon showing up on google results page

### ISSUE THREAD

**Issue by FridIsar** [Abdulrahman-salem/React-app-Portfolio-MigraCode#69]
We are seeing the React Icon instead of MigraCode's. 
This one may be the culprit!
https://github.com/Abdulrahman-salem/React_MigraCode_portfolio/blob/af6c38bc295be13f0b7e38c459a7b231acea213b/public/index.html#L22
It is also recommended to delete both png files containing React's icon

**Comment by Abdulrahman-salem** [comment]
Fixed in #70

**Comment by Abdulrahman-salem** [comment]
Solved in #70
